name: Sprint5 Full Automation

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Instalar dependências Python
        run: pip install -r requirements.txt

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Apply
        working-directory: infra
        run: |
          terraform init
          terraform apply -auto-approve

      - name: Obter IP da EC2 do Terraform
        id: ec2
        working-directory: infra
        run: |
          echo "EC2_IP=$(terraform output -raw ec2_public_ip)" >> $GITHUB_ENV

      - name: Configurar EC2 com Ansible
        working-directory: ansible
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
        run: |
          ansible-playbook -i "$EC2_IP," -u ec2-user --private-key ~/.ssh/mykey.pem setup.yml

      - name: Executar pipeline de dados
        run: python scripts/data_pipeline.py

